### ISSUE TITLE
Circom Plonk Support Tracking Issue

### ISSUE THREAD

**Issue by dkales** [TaceoLabs/collaborative-circom#131]
- [X] Circom Types for Plonk #128 
- [x] Plonk Prover
  - [x] Product Argument
- [x] Plain PLONK Verifier
- [x] E2E testing
- [x] Crate organization 
- [ ] Optimizations

## sub tasks
- [x] serialize proof and verify with cirocm
- [x] build interface to call PLONK like for Groth16
- [x] MPC tests
- [x] clean up
- [x] tackle todos

**Comment by 0xThemis** [comment]
close this issue because of #136 ??
